import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:intl/intl.dart';
import '../../../core/theme/app_theme.dart';
import '../../../data/local/database/app_database.dart';
import '../../../providers/repository_providers.dart';

/// Adaptive Tasks Screen - Shows daily decisions generated by the adaptive engine
class AdaptiveTasksScreen extends ConsumerStatefulWidget {
  const AdaptiveTasksScreen({super.key});

  @override
  ConsumerState<AdaptiveTasksScreen> createState() =>
      _AdaptiveTasksScreenState();
}

class _AdaptiveTasksScreenState extends ConsumerState<AdaptiveTasksScreen> {
  DateTime _selectedDate = DateTime.now();
  bool _isGenerating = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Smart Farming Tasks'),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: _generateTodaysDecisions,
          ),
        ],
      ),
      body: Column(
        children: [
          _buildDateSelector(),
          Expanded(
            child: _buildDecisionsList(),
          ),
        ],
      ),
    );
  }

  Widget _buildDateSelector() {
    return Container(
      padding: EdgeInsets.all(16.w),
      decoration: BoxDecoration(
        color: AppColors.surface,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          IconButton(
            icon: const Icon(Icons.chevron_left),
            onPressed: () {
              setState(() {
                _selectedDate = _selectedDate.subtract(const Duration(days: 1));
              });
            },
          ),
          Expanded(
            child: InkWell(
              onTap: _selectDate,
              child: Column(
                children: [
                  Text(
                    DateFormat('EEEE').format(_selectedDate),
                    style: AppTextStyles.bodyMedium.copyWith(
                      color: AppColors.textSecondary,
                    ),
                  ),
                  SizedBox(height: 4.h),
                  Text(
                    DateFormat('MMM dd, yyyy').format(_selectedDate),
                    style: AppTextStyles.h3,
                  ),
                  if (_isToday(_selectedDate))
                    Container(
                      margin: EdgeInsets.only(top: 4.h),
                      padding:
                          EdgeInsets.symmetric(horizontal: 8.w, vertical: 2.h),
                      decoration: BoxDecoration(
                        color: AppColors.primary.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(4.r),
                      ),
                      child: Text(
                        'Today',
                        style: AppTextStyles.bodySmall.copyWith(
                          color: AppColors.primary,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                ],
              ),
            ),
          ),
          IconButton(
            icon: const Icon(Icons.chevron_right),
            onPressed: _selectedDate.isBefore(
              DateTime.now().subtract(const Duration(days: 1)),
            )
                ? () {
                    setState(() {
                      _selectedDate =
                          _selectedDate.add(const Duration(days: 1));
                    });
                  }
                : null,
          ),
        ],
      ),
    );
  }

  Widget _buildDecisionsList() {
    final userIdAsync = ref.watch(currentUserIdProvider);

    return userIdAsync.when(
      data: (userId) {
        if (userId == null) {
          return const Center(child: Text('Please log in'));
        }

        final decisionsAsync = ref.watch(
          todaysDecisionsProvider(userId),
        );

        return decisionsAsync.when(
          data: (decisions) {
            // Filter by selected date
            final filteredDecisions = decisions.where((d) {
              return d.decisionDate.year == _selectedDate.year &&
                  d.decisionDate.month == _selectedDate.month &&
                  d.decisionDate.day == _selectedDate.day;
            }).toList();

            if (_isGenerating) {
              return const Center(child: CircularProgressIndicator());
            }

            if (filteredDecisions.isEmpty) {
              return _buildEmptyState(userId);
            }

            return RefreshIndicator(
              onRefresh: () async {
                await _generateTodaysDecisions();
              },
              child: ListView.builder(
                padding: EdgeInsets.all(16.w),
                itemCount: filteredDecisions.length,
                itemBuilder: (context, index) {
                  return _buildDecisionCard(filteredDecisions[index]);
                },
              ),
            );
          },
          loading: () => const Center(child: CircularProgressIndicator()),
          error: (error, stack) => Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.error_outline, size: 64.sp, color: AppColors.error),
                SizedBox(height: 16.h),
                Text('Error: $error', style: AppTextStyles.bodyMedium),
              ],
            ),
          ),
        );
      },
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, stack) => Center(child: Text('Error: $error')),
    );
  }

  Widget _buildEmptyState(String userId) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.agriculture_outlined,
            size: 80.sp,
            color: AppColors.textSecondary,
          ),
          SizedBox(height: 16.h),
          Text(
            _isToday(_selectedDate)
                ? 'No tasks for today'
                : 'No tasks for this date',
            style: AppTextStyles.h3,
          ),
          SizedBox(height: 8.h),
          Text(
            _isToday(_selectedDate)
                ? 'Generate today\'s farming recommendations'
                : 'Select today to generate recommendations',
            style: AppTextStyles.bodyMedium.copyWith(
              color: AppColors.textSecondary,
            ),
            textAlign: TextAlign.center,
          ),
          if (_isToday(_selectedDate)) ...[
            SizedBox(height: 24.h),
            ElevatedButton.icon(
              onPressed: _generateTodaysDecisions,
              icon: const Icon(Icons.auto_awesome),
              label: const Text('Generate Tasks'),
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildDecisionCard(DailyDecision decision) {
    final priorityColor = _getPriorityColor(decision.priority);
    final typeIcon = _getDecisionTypeIcon(decision.decisionType);

    return Card(
      margin: EdgeInsets.only(bottom: 12.h),
      child: InkWell(
        onTap: () => _showDecisionDetails(decision),
        borderRadius: BorderRadius.circular(12.r),
        child: Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(12.r),
            border: Border.all(
              color: decision.isCompleted
                  ? AppColors.success.withOpacity(0.3)
                  : priorityColor.withOpacity(0.3),
              width: 2,
            ),
          ),
          child: Padding(
            padding: EdgeInsets.all(16.w),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Container(
                      padding: EdgeInsets.all(8.w),
                      decoration: BoxDecoration(
                        color: priorityColor.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(8.r),
                      ),
                      child: Icon(typeIcon, color: priorityColor, size: 24.sp),
                    ),
                    SizedBox(width: 12.w),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            decision.title,
                            style: AppTextStyles.bodyLarge.copyWith(
                              fontWeight: FontWeight.w600,
                              decoration: decision.isCompleted
                                  ? TextDecoration.lineThrough
                                  : null,
                            ),
                          ),
                          SizedBox(height: 4.h),
                          Row(
                            children: [
                              _buildChip(
                                decision.decisionType
                                    .replaceAll('_', ' ')
                                    .toUpperCase(),
                                priorityColor,
                              ),
                              SizedBox(width: 8.w),
                              _buildChip(
                                _getPriorityLabel(decision.priority),
                                priorityColor,
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                    if (decision.isCompleted)
                      Icon(Icons.check_circle,
                          color: AppColors.success, size: 28.sp)
                    else
                      Checkbox(
                        value: false,
                        onChanged: (value) => _completeDecision(decision),
                      ),
                  ],
                ),
                SizedBox(height: 12.h),
                Text(
                  decision.description,
                  style: AppTextStyles.bodyMedium.copyWith(
                    color: AppColors.textSecondary,
                  ),
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
                SizedBox(height: 8.h),
                Row(
                  children: [
                    Icon(Icons.info_outline,
                        size: 16.sp, color: AppColors.primary),
                    SizedBox(width: 4.w),
                    Text(
                      'Tap to see why',
                      style: AppTextStyles.bodySmall.copyWith(
                        color: AppColors.primary,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildChip(String label, Color color) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 8.w, vertical: 4.h),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(4.r),
      ),
      child: Text(
        label,
        style: AppTextStyles.bodySmall.copyWith(
          color: color,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Future<void> _showDecisionDetails(DailyDecision decision) async {
    await showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => DraggableScrollableSheet(
        initialChildSize: 0.7,
        maxChildSize: 0.9,
        minChildSize: 0.5,
        builder: (context, scrollController) => Container(
          decoration: BoxDecoration(
            color: AppColors.surface,
            borderRadius: BorderRadius.vertical(top: Radius.circular(20.r)),
          ),
          padding: EdgeInsets.all(20.w),
          child: ListView(
            controller: scrollController,
            children: [
              Row(
                children: [
                  Expanded(
                    child: Text(decision.title, style: AppTextStyles.h3),
                  ),
                  IconButton(
                    icon: const Icon(Icons.close),
                    onPressed: () => Navigator.pop(context),
                  ),
                ],
              ),
              SizedBox(height: 16.h),
              Text(
                decision.description,
                style: AppTextStyles.bodyLarge,
              ),
              SizedBox(height: 24.h),
              _buildSection('Why This Recommendation?', decision.reasoning),
              if (decision.aiExplanation != null) ...[
                SizedBox(height: 16.h),
                _buildSection('AI Insights', decision.aiExplanation!),
              ],
              SizedBox(height: 24.h),
              if (!decision.isCompleted) ...[
                ElevatedButton.icon(
                  onPressed: () {
                    Navigator.pop(context);
                    _completeDecision(decision);
                  },
                  icon: const Icon(Icons.check),
                  label: const Text('Mark as Complete'),
                  style: ElevatedButton.styleFrom(
                    padding: EdgeInsets.symmetric(vertical: 12.h),
                  ),
                ),
              ] else ...[
                Container(
                  padding: EdgeInsets.all(12.w),
                  decoration: BoxDecoration(
                    color: AppColors.success.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8.r),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.check_circle,
                          color: AppColors.success, size: 24.sp),
                      SizedBox(width: 12.w),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Completed',
                              style: AppTextStyles.bodyLarge.copyWith(
                                color: AppColors.success,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                            if (decision.completedAt != null)
                              Text(
                                DateFormat('MMM dd, yyyy at hh:mm a')
                                    .format(decision.completedAt!),
                                style: AppTextStyles.bodySmall.copyWith(
                                  color: AppColors.textSecondary,
                                ),
                              ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: AppTextStyles.h4.copyWith(
            color: AppColors.primary,
          ),
        ),
        SizedBox(height: 8.h),
        Container(
          padding: EdgeInsets.all(12.w),
          decoration: BoxDecoration(
            color: AppColors.primary.withOpacity(0.05),
            borderRadius: BorderRadius.circular(8.r),
            border: Border.all(
              color: AppColors.primary.withOpacity(0.2),
            ),
          ),
          child: Text(
            content,
            style: AppTextStyles.bodyMedium,
          ),
        ),
      ],
    );
  }

  Future<void> _completeDecision(DailyDecision decision) async {
    try {
      final decisionRepo = ref.read(dailyDecisionRepositoryProvider);
      await decisionRepo.completeDecision(decisionId: decision.id);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('Task completed! 🎉'),
          backgroundColor: AppColors.success,
        ),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error: $e'),
          backgroundColor: AppColors.error,
        ),
      );
    }
  }

  Future<void> _generateTodaysDecisions() async {
    if (!_isToday(_selectedDate)) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Can only generate tasks for today')),
      );
      return;
    }

    setState(() => _isGenerating = true);

    try {
      final authRepo = ref.read(authRepositoryProvider);
      final userId = await authRepo.getCurrentUserId();

      if (userId == null) {
        throw Exception('User not logged in');
      }

      final decisionRepo = ref.read(dailyDecisionRepositoryProvider);
      final weatherRepo = ref.read(weatherRepositoryProvider);

      // Try to get weather data (optional)
      Map<String, dynamic>? weatherData;
      try {
        // Assuming user has at least one field with coordinates
        final database = ref.read(databaseProvider);
        final fields = await database.getFieldsByUserId(userId);

        if (fields.isNotEmpty) {
          // Use first field's location (you could improve this logic)
          final weather = await weatherRepo.getWeatherData(
            0, // latitude - would come from field coordinates
            0, // longitude - would come from field coordinates
          );

          if (weather.isNotEmpty) {
            weatherData = {
              'temperature': weather['temperature'],
              'rainfall': weather['precipitation'],
              'humidity': weather['humidity'],
            };
          }
        }
      } catch (e) {
        // Weather not available, continue without it
      }

      final generatedIds = await decisionRepo.generateAllActiveDecisions(
        userId: userId,
        weatherData: weatherData,
      );

      setState(() => _isGenerating = false);

      if (!mounted) return;

      if (generatedIds.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text(
                'No active crops found. Start a crop on your field first.'),
          ),
        );
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Generated ${generatedIds.length} task(s) 🌱'),
            backgroundColor: AppColors.success,
          ),
        );
      }
    } catch (e) {
      setState(() => _isGenerating = false);
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error: $e'),
          backgroundColor: AppColors.error,
        ),
      );
    }
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now().subtract(const Duration(days: 365)),
      lastDate: DateTime.now(),
    );

    if (picked != null) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  bool _isToday(DateTime date) {
    final now = DateTime.now();
    return date.year == now.year &&
        date.month == now.month &&
        date.day == now.day;
  }

  Color _getPriorityColor(int priority) {
    switch (priority) {
      case 2:
        return AppColors.error;
      case 1:
        return AppColors.warning;
      default:
        return AppColors.primary;
    }
  }

  String _getPriorityLabel(int priority) {
    switch (priority) {
      case 2:
        return 'HIGH';
      case 1:
        return 'MEDIUM';
      default:
        return 'LOW';
    }
  }

  IconData _getDecisionTypeIcon(String type) {
    switch (type.toLowerCase()) {
      case 'action':
        return Icons.task_alt;
      case 'observation':
        return Icons.visibility;
      case 'decision_window':
        return Icons.access_time;
      default:
        return Icons.info;
    }
  }
}
